### ISSUE TITLE
Safe backlight handling not triggered for bad LCDs

### ISSUE THREAD

**Issue by inzanity** [duinoWitchery/hd44780#10]
Commit 0cf7441 introduced an invalid check `_bl == HIGH`, which makes the broken backlight check only happen on boards where backlight is controlled by D1. The correct check would be `_blLevel == HIGH`.

**Comment by bperrybap** [comment]
Wow. That is a serious bug.  Thank you for pointing this out.
I will release an update to fix this ASAP.

**Comment by bperrybap** [comment]
fixed in latest release (1.1.0) with commit ac405aa582d94d19c372be062cac1123ec1173a9
