### ISSUE TITLE
simple examples

### ISSUE THREAD

**Issue by darkworks** [duinoWitchery/hd44780#11]
hi 
can u please add some quick start simple examples to this lib , current examples are big full of tons of comments , i guess some short quick start examples like this i2c liquid crystal display libs will be good , like include lib and init.lib  and print something hello to screen  . Or quick start is not possible with this lib 

```
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x27,20,4);  // set the LCD address to 0x27 for a 16 chars and 2 line display

void setup()
{
  lcd.init();                      // initialize the lcd 
  // Print a message to the LCD.
  lcd.backlight();
  lcd.setCursor(3,0);
  lcd.print("Hello, world!");
  lcd.setCursor(2,1);
  lcd.print("Ywrobot Arduino!");
   lcd.setCursor(0,2);
  lcd.print("Arduino LCM IIC 2004");
   lcd.setCursor(2,3);
  lcd.print("Power By Ec-yuan!");
}
```

but these libs have issues like it just print one character on screen

**Comment by bperrybap** [comment]
The code you have posted is not for this library.
The hd44780 library includes several different i/o classes for different h/w interfaces.
i.e. 4 bit mode using direct pin i/o, i2c expansion backpacks, lcds with direct i2c interfaces, and a few for NoriTake devices.

Each i/o class has its own examples, including a HelloWorld sketch.
The hd44780  library also comes with extensive documentation, that can be accessed using the **Documentation** sketch.
The github repository also has documentation. It has a readme that with lots of information including, supported h/w, how to install the library, and API summary, and a revision log. (all this is also available in the documentation that comes with the library).
The github repository also includes a wiki with some additional available information. The wiki is also available through the documentation that comes with the library.
