### ISSUE TITLE
Typos in readme

### ISSUE THREAD

**Issue by HendrikVE** [duinoWitchery/hd44780#18]
When reading through the readme I noticed two small typos in: `how to isntall them` and `click on: [File]->Prefernces`.

**Comment by bperrybap** [comment]
Thank you.
It is always good to have extra eyes looking over things.
They have been corrected and it will show up in the next release.
I'll close the issue when the next version is released.

**Comment by bperrybap** [comment]
fixed in 1.3.2 release
