### ISSUE TITLE
choose different SDA and SCL pins?

### ISSUE THREAD

**Issue by Irgendwer008** [duinoWitchery/hd44780#32]
is it possible to change the SDA and SCL pins for i2c? i am using an STM32F103C8T6 Board and with the normal pins everything works fine but i'd like to change the pins from the standart Wire-library pins (I think PB7 and PB6) to PB11 and PB10. Is that possible somehow?

**Comment by bperrybap** [comment]
This is outside the hd44780 library as the hd44780 library does not have any code to control the i2c interface or its pins.

It appears that the STM32 platform has Wire library API extensions for setting the pins.
```
Wire.setSDA(sdapin);
Wire.setSCL(sclpin);
```

Or both at same time:
`Wire.begin(sdapin, sclpin);`

https://www.stm32duino.com/viewtopic.php?t=1047


You will need to configure the pins before you call the hd44780 lcd.begin() function.

**Comment by Irgendwer008** [comment]
alright thanks, i'll look into it (but tomorrow its 2am here lol)
but thanks for the fast reply!

**Comment by Irgendwer008** [comment]
Thanks @bperrybap for the help (and your amazing work in general), it worked great for me!

for any future people, here is my code for a Hello, World! programm:

```
#include <Wire.h>

TwoWire WIRE1 (2,I2C_FAST_MODE);
#define Wire WIRE1

#include <hd44780.h>
#include <hd44780ioClass/hd44780_I2Cexp.h>

hd44780_I2Cexp lcd;


void setup() {
  lcd.begin(16, 2);
  lcd.print("Hello, World!");
}

void loop() {
  
}
```
this works because i am using the second set of i2c-pins on the STM32 (therefor the "2" in TwoWire WIRE1 (_**2**_,I2C_FAST_MODE); ), but im sure choosing any pins is possible in a similar way with something like
> ```
> Wire.setSDA(sdapin);
> Wire.setSCL(sclpin);
> ```
> 
> Or both at same time: `Wire.begin(sdapin, sclpin);`

although i have not tried that yet since there is no need for me.
