### ISSUE TITLE
Help with Mega 2560

### ISSUE THREAD

**Issue by melucas** [duinoWitchery/hd44780#9]
Great library!  It works well with my UNO.  However, for my project, I need more IO ports, so I am moving to a Mega 2560.  When I use the hd44780 library with the Mega, the display only shows the first line of square blocks.  If I switch back to the LiquidCrystal library the screen and buttons work correctly.

I want to use your library because I have an LCD Keypad Shield which has the backlight bug/defect and I need to be able to turn the backlight off to conserve battery power.

Any suggestions?

**Comment by bperrybap** [comment]
Start a thread on the Arduino forum under the "Displays" section.
I'll look for it and respond there.
